/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tshirt1.gltf 
Author: Nayeem (https://sketchfab.com/nayem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-7018d8578d6b4ee7af010d26eda1ecc9
Title: T-shirt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tshirt1.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.537, -218.685, -0.537]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Design_mat_0_Inside_Mat_0_0.geometry} material={materials.Mat_0} />
            <mesh geometry={nodes.Design_mat_0_Outside_Mat_1_0.geometry} material={materials.Mat_1} />
            <mesh geometry={nodes.Design_mat_1_Inside_Mat_0_0.geometry} material={materials.Mat_0} />
            <mesh geometry={nodes.Design_mat_1_Outside_Mat_1_0.geometry} material={materials.Mat_1} />
            <mesh geometry={nodes.Design_mat_2_Inside_Mat_0_0.geometry} material={materials.Mat_0} />
            <mesh geometry={nodes.Design_mat_2_Outside_Mat_1_0.geometry} material={materials.Mat_1} />
            <mesh geometry={nodes.Design_mat_3_Inside_Mat_0_0.geometry} material={materials.Mat_0} />
            <mesh geometry={nodes.Design_mat_3_Outside_Mat_1_0.geometry} material={materials.Mat_1} />
            <mesh geometry={nodes.Design_mat_4_Inside_Mat_0_0.geometry} material={materials.Mat_0} />
            <mesh geometry={nodes.Design_mat_4_Outside_Mat_1_0.geometry} material={materials.Mat_1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tshirt1.gltf')
