/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 denim.gltf 
Author: Digital Fashionwear (DF) (https://sketchfab.com/digitalfashionwear)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unisex-denim-shirt-design-a685d590d0724ea4a27aeb2aaa851c89
Title: Unisex Denim Shirt Design
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/images/denim/denim.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.DF_Denim_FRONT_2670}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.DF_Denim_FRONT_2670}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.DF_Denim_FRONT_2670}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.DF_Denim_FRONT_2670}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.DF_Denim_FRONT_2670}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.DF_Denim_FRONT_2670}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.DF_Denim_FRONT_2670}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Material1041664}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/images/denim/denim.gltf");
