/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Skirt_Tshirt.gltf 
Author: Virtual Pandora (https://sketchfab.com/virtualpandora)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skirt-and-t-shirt-e0ea80504d914211a96a8c36a4e1a4db
Title: Skirt and t-shirt
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/images/skirt_and_t-shirt/Skirt_Tshirt.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.PT_FABRIC_FRONT_12672}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.pocket_FRONT_4391}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.skirt_FRONT_4383}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["t-shirt_FRONT_4377"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/images/skirt_and_t-shirt/Skirt_Tshirt.gltf");
