/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 t2.gltf 
Author: Dubel (https://sketchfab.com/yshkyren)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/clothes-pants-c331e2539662492baed49e4c8d2c8190
Title: Clothes: Pants
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function T2(props) {
  const { nodes, materials } = useGLTF('/images/t2.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/images/t2.gltf')
